name = "katelyatv"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm install --frozen-lockfile && pnpm run pages:build"

[[build.environment_variables]]
NEXT_PUBLIC_STORAGE_TYPE = "localstorage"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "123456"
NEXT_PUBLIC_ENABLE_REGISTER = "true"
